In [1]:
import pandas as pd

In [2]:
a=pd.Series([90,85,72],
            index=["amit","riya","sam"])
data={
    "name":["amit","riya","sam"],
    "marks":[90,85,72],
    "city":["delhi","pune","goa"],
}
df=pd.DataFrame(data)
print(df)

   name  marks   city
0  amit     90  delhi
1  riya     85   pune
2   sam     72    goa

In [5]:
import pandas as pd

In [6]:
print(pd.__version__)

3.0.6

In [7]:
s= pd.Series([90,85,72],
             index=["riya", "amit", "sam"])

In [8]:
print(s)

riya    90
amit    85
sam     72
dtype: int64

In [21]:
s=pd.Series([90,85,47,65,85,45,75,23,22,21],
            index=["amit","sam","sushil","aman","ankit","raman","rohan","navi","vikas","pranav"])

In [22]:
print(s)

amit      90
sam       85
sushil    47
aman      65
ankit     85
raman     45
rohan     75
navi      23
vikas     22
pranav    21
dtype: int64

In [23]:
s.head()

amit      90
sam       85
sushil    47
aman      65
ankit     85
dtype: int64

In [24]:
s.tail()

raman     45
rohan     75
navi      23
vikas     22
pranav    21
dtype: int64

In [25]:
s.info()

<class 'pandas.Series'>
Index: 10 entries, amit to pranav
Series name: None
Non-Null Count  Dtype
--------------  -----
10 non-null     int64
dtypes: int64(1)
memory usage: 160.0+ bytes

In [26]:
s.describe()

count    10.000000
mean     55.800000
std      27.792085
min      21.000000
25%      28.500000
50%      56.000000
75%      82.500000
max      90.000000
dtype: float64

In [28]:
s.shape

(10,)

In [31]:
df.columns

Index(['name', 'marks', 'city'], dtype='str')

In [32]:
import pandas as pd

In [10]:
df=pd.read_csv("std.csv")
print(df)

   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67     NaN       65
4         105        Rohit     NaN      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89      NaN
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110          NaN      81      84  seventy

In [35]:
df.isna()

   Student_ID  Student_Name  English  Maths  Science
0       False         False    False  False    False
1       False         False    False  False    False
2       False         False    False  False    False
3       False         False    False   True    False
4       False         False     True  False    False
5       False         False    False  False    False
6       False         False    False  False     True
7       False         False    False  False    False
8       False         False    False  False    False
9       False          True    False  False    False

In [36]:
df.isna().sum()

Student_ID      0
Student_Name    1
English         1
Maths           1
Science         1
dtype: int64

In [37]:
df.dropna()

   Student_ID Student_Name English   Maths Science
0         101        Rahul      78      88      82
1         102        Priya      85      91      79
2         103         Aman  ninety      76      88
5         106       Simran      92  eighty      90
7         108       Anjali      74      72      77
8         108       Anjali      74      72      77

In [38]:
df.fillna(0)

   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67       0       65
4         105        Rohit       0      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89        0
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110            0      81      84  seventy

In [39]:
df.fillna(2)

   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67       2       65
4         105        Rohit       2      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89        2
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110            2      81      84  seventy

In [6]:
print(df)

   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67     NaN       65
4         105        Rohit     NaN      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89      NaN
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110          NaN      81      84  seventy

In [11]:
import pandas as pd
df=pd.read_csv("std.csv")

In [13]:
df.to_excel("pranav.xlsx")

In [14]:
print(df)

   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67     NaN       65
4         105        Rohit     NaN      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89      NaN
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110          NaN      81      84  seventy

In [15]:
df.to_csv("pranav.csv")

In [16]:
df

   Student_ID Student_Name English   Maths  Science
0         101        Rahul      78      88       82
1         102        Priya      85      91       79
2         103         Aman  ninety      76       88
3         104         Neha      67     NaN       65
4         105        Rohit     NaN      95      101
5         106       Simran      92  eighty       90
6         107        Vikas     105      89      NaN
7         108       Anjali      74      72       77
8         108       Anjali      74      72       77
9         110          NaN      81      84  seventy